---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: recommendationservice
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: recommendationservice
  policy:
    semver:
      range: '>=0.2.0 <0.3.0'
