---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: recommendationservice
  namespace: flux-system
spec:
  image: registry.deepfence.net/recommendationservice
  interval: 30s
  secretRef:
    name: registry.deepfence.net
